module.exports = [
  {
    name: 'Javascript',
    level: 'Proficient',
    category: 'Front-End',
    toolTip: 'My primary programming language :)',
    id: 1,
  },
  {
    name: 'HTML',
    level: 'Intermediate',
    category: 'Front-End',
    toolTip: 'My app logic is usually created with a front end library written in jsx, compiled in a bundle file and linked to the HTML file.',
    id: 2,
  },
  {
    name: 'CSS',
    level: 'Proficient',
    category: 'Front-End',
    toolTip: 'This website was styled by me from scratch using CSS Modules.',
    id: 3,
  },
  {
    name: 'React.js',
    level: 'Proficient',
    category: 'Front-End',
    toolTip: 'My favourite front end framework. This website was created with React.js.',
    id: 4,
  },
  {
    name: 'jQuery',
    level: 'Intermediate',
    category: 'Front-End',
    toolTip: 'I am proficient developing with jQuery.',
    id: 5,
  },
  {
    name: 'Node.js/Express',
    level: 'Proficient',
    category: 'Back-End',
    toolTip: 'My weapon of choice for all things back end.',
    id: 6,
  },
  {
    name: 'MongoDB',
    level: 'Proficient',
    category: 'Back-End',
    toolTip: 'I have set up many MongoDB databases and have experience with Mongoose and native Mongo methods. My Lodging Marketplace App uses MongoDB.',
    id: 7,
  },
  {
    name: 'PostgreSQL',
    level: 'Intermediate',
    category: 'Back-End',
    toolTip: 'I have experience scaling a PostgreSQL app (my Movie Reviews App) to over 100 million records, creating custom SQL files for initialization and SQL commands for CRUD app functionality.',
    id: 8,
  },
  {
    name: 'MySQL',
    level: 'Basic',
    category: 'Back-End',
    toolTip: 'I have experience setting up MySQL (with Sequelize) for CRUD functionality.',
    id: 9,
  },
  {
    name: 'Git/Github',
    level: 'Proficient',
    category: 'Tools',
    toolTip: 'All of my development uses Git workflow. Use the link on the landing page to check out my profile :)',
    id: 10,
  },
  {
    name: 'npm',
    level: 'Proficient',
    category: 'Tools',
    toolTip: 'The Node.js package manager I use.',
    id: 11,
  },
  {
    name: 'Webpack',
    level: 'Intermediate',
    category: 'Tools',
    toolTip: 'Used to transpile and bundle jsx files into pure JavaScript so it can be run in the browser.',
    id: 12,
  },
  {
    name: 'K6.io',
    level: 'Intermediate',
    category: 'Tools',
    toolTip: 'An open source load testing tool. I used it to stress test my Movie Reviews App locally.',
    id: 13,
  },
  {
    name: 'Loader.io',
    level: 'Proficient',
    category: 'Tools',
    toolTip: 'A cloud based load testing tool. I stress tested my AWS deployed Movie Reviews App using payload files to simulate production.',
    id: 14,
  },
  {
    name: 'Cypress.io',
    level: 'Basic',
    category: 'Tools',
    toolTip: 'An end to end testing library. I used this to test the pagination micro-service on my Lodging Marketplace App.',
    id: 15,
  },
  {
    name: 'Mocha/Chai',
    level: 'Intermediate',
    category: 'Tools',
    toolTip: 'Mocha is a JavaScript testing framework and Chai is an assertion library. I have used these together to test pure JavaScript.',
    id: 16,
  },
  {
    name: 'Jest/Enzyme',
    level: 'Basic',
    category: 'Tools',
    toolTip: 'Jest is a JavaScript unit testing framework and Enzyme is a testing utility for React.js. I have used them to test React.js components.',
    id: 17,
  },
  {
    name: 'AWS (EC2/S3)',
    level: 'Proficient',
    category: 'Tools',
    toolTip: 'I have deployed various applications and databases to EC2 instances. I host all images for my apps on S3 to increase load speed.',
    id: 18,
  },
  {
    name: 'Heroku',
    level: 'Proficient',
    category: 'Tools',
    toolTip: 'I have deployed multiple apps to Heroku.',
    id: 19,
  },
  {
    name: 'RESTful API',
    level: 'Proficient',
    category: 'Other',
    toolTip: 'The APIs for all my projects that include a back end follow RESTful principles.',
    id: 20,
  },
  {
    name: 'Agile',
    level: 'Proficient',
    category: 'Other',
    toolTip: 'I have extensive experience with agile practices such as daily stand-ups, pair programming, reflectives, sprints, etc.',
    id: 21,
  },
  {
    name: 'TDD',
    level: 'Proficient',
    category: 'Other',
    toolTip: 'I have experience navigating large testing suites as well as developing my own unit, integration and E2E tests.',
    id: 22,
  },
  {
    name: 'Eslint',
    level: 'Proficient',
    category: 'Tools',
    toolTip: 'Everyone makes mistakes. A linter is very helpful in catching those errors before they break production :P',
    id: 23,
  },
  {
    name: 'Trello',
    level: 'Proficient',
    category: 'Tools',
    toolTip: 'A Ticketing tool which helps keep projects and teams organized and efficient.',
    id: 24,
  },
  {
    name: 'MVC',
    level: 'Proficient',
    category: 'Other',
    toolTip: 'The Model-View-Controller software design pattern allows for separation of concerns and modularization.',
    id: 25,
  },
  {
    name: 'SPA',
    level: 'Proficient',
    category: 'Other',
    toolTip: 'Single Page Application development',
    id: 26,
  },
];
